<?php defined('SYSPATH') or die('No direct script access');

return [
    'trusted_hosts' => [
        'glopro.\.ru',
        '.*\.glopro\.ru',
        'oilst\.ru',
        '.*\.oilst\.ru',
        'vegih\.com',
        '.*\.vegih\.com',
        'piteroilcard\.ru',
        '.*\.piteroilcard\.ru',
        'interoil51\.ru',
        '.*\.interoil51\.ru',
        'neftregion\.ru',
        '.*\.neftregion\.ru',
        'skala-card\.ru',
        '.*\.skala-card\.ru',
        'modulcard\.ru',
        '.*\.modulcard\.ru',
        'alberit\.ru',
        '.*\.alberit\.ru',
        'cleveroil\.ru',
        '.*\.cleveroil\.ru',
        'gpn-card\.com',
        '.*\.gpn-card\.com',
        'bin-oil\.com',
        '.*\.bin-oil\.com',
        'tway\.pro',
        '.*\.tway\.pro',
    ],
];